param(
  [string]$Workspaces = $env:POWERBI_KNOWN_WORKSPACES,
  [string]$Workspace = $env:POWERBI_DEFAULT_WORKSPACE,
  [string]$Model = $env:POWERBI_DEFAULT_SEMANTIC_MODEL,
  [string]$ReportDir = $env:POWERBI_REPORT_OUTPUT_DIR,
  [string]$Config = "",
  [string]$Name = "mcp-powerBI-to-report",
  [string]$ModelingCommand = $env:POWERBI_MODELING_MCP_COMMAND,
  [string]$ModelingArgs = $env:POWERBI_MODELING_MCP_ARGS,
  [switch]$SkipInstall,
  [switch]$DryRun
)

$ErrorActionPreference = "Stop"

function Require-Command($Name) {
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Missing required command: $Name"
  }
}

function First-CsvValue($Value) {
  if (-not $Value) { return "" }
  return (($Value -split ",") | ForEach-Object { $_.Trim() } | Where-Object { $_ } | Select-Object -First 1)
}

function Get-ClaudeConfigPath {
  if ($Config) { return $Config }

  $standard = Join-Path $env:APPDATA "Claude\claude_desktop_config.json"
  $packages = Join-Path $env:LOCALAPPDATA "Packages"
  if (Test-Path $packages) {
    $msix = Get-ChildItem $packages -Directory -Filter "Claude_*" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($msix) {
      $candidate = Join-Path $msix.FullName "LocalCache\Roaming\Claude\claude_desktop_config.json"
      if (Test-Path $candidate) { return $candidate }
    }
  }
  return $standard
}

Require-Command node
Require-Command npm

$RepoDir = Split-Path -Parent $PSScriptRoot
if (-not $Workspaces -and $Workspace) {
  $Workspaces = $Workspace
}
if (-not $Workspaces) { $Workspaces = "test-mcp" }
if (-not $Workspace) { $Workspace = First-CsvValue $Workspaces }
if (-not $ReportDir) { $ReportDir = Join-Path $HOME "powerbi-report-output" }
if (-not $ModelingArgs) { $ModelingArgs = "--start --authmode=interactive" }

Set-Location $RepoDir

if (-not $SkipInstall -and -not $DryRun) {
  npm install --omit=dev --include=optional
}

$NativeModelingBinary = Join-Path $RepoDir "node_modules\@microsoft\powerbi-modeling-mcp-win32-x64\dist\powerbi-modeling-mcp.exe"
if (-not $ModelingCommand) {
  if (Test-Path $NativeModelingBinary) {
    $ModelingCommand = $NativeModelingBinary
  } else {
    throw "Cannot find Microsoft Modeling MCP Windows binary at: $NativeModelingBinary. Run npm install --omit=dev --include=optional, then re-run this script."
  }
}

$ConfigPath = Get-ClaudeConfigPath
$ServerJs = Join-Path $RepoDir "dist\server.js"

if ($DryRun) {
  [ordered]@{
    Repo = $RepoDir
    ClaudeConfig = $ConfigPath
    ServerJs = $ServerJs
    ModelingCommand = $ModelingCommand
    ModelingArgs = $ModelingArgs
    KnownWorkspaces = $Workspaces
    DefaultWorkspace = $Workspace
    DefaultSemanticModel = $Model
    ReportDir = $ReportDir
  } | Format-List
  exit 0
}

if (-not (Test-Path $ServerJs)) {
  throw "Missing prebuilt server: $ServerJs. Use the GitHub main branch that includes dist/server.js, or run npm install && npm run build on a development machine."
}
New-Item -ItemType Directory -Force -Path $ReportDir | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $ConfigPath) | Out-Null

if (Test-Path $ConfigPath) {
  Copy-Item $ConfigPath "$ConfigPath.bak.$(Get-Date -Format yyyyMMddHHmmss)"
  $raw = (Get-Content $ConfigPath -Raw).Trim()
  if ($raw) {
    $configObject = $raw | ConvertFrom-Json
  } else {
    $configObject = [pscustomobject]@{}
  }
} else {
  $configObject = [pscustomobject]@{}
}

$config = @{}
foreach ($property in $configObject.PSObject.Properties) {
  $config[$property.Name] = $property.Value
}
if (-not $config.ContainsKey("mcpServers") -or -not $config["mcpServers"]) {
  $config["mcpServers"] = [pscustomobject]@{}
}

$mcpServers = @{}
foreach ($property in $config["mcpServers"].PSObject.Properties) {
  $mcpServers[$property.Name] = $property.Value
}

$envMap = [ordered]@{
  POWERBI_KNOWN_WORKSPACES = $Workspaces
  POWERBI_DEFAULT_WORKSPACE = $Workspace
  POWERBI_MODELING_MCP_COMMAND = $ModelingCommand
  POWERBI_MODELING_MCP_ARGS = $ModelingArgs
  POWERBI_REPORT_OUTPUT_DIR = $ReportDir
}
if ($Model) {
  $envMap["POWERBI_DEFAULT_SEMANTIC_MODEL"] = $Model
}

$mcpServers[$Name] = [ordered]@{
  command = "node"
  args = @($ServerJs)
  env = $envMap
}
$config["mcpServers"] = $mcpServers

$config | ConvertTo-Json -Depth 20 | Set-Content -Path $ConfigPath -Encoding UTF8

$envPath = Join-Path $RepoDir ".env"
$envLines = @("# Generated by scripts/setup-claude-desktop.ps1")
foreach ($item in $envMap.GetEnumerator()) {
  $jsonValue = $item.Value | ConvertTo-Json -Compress
  $envLines += "$($item.Key)=$jsonValue"
}
$envLines += ""
$envLines | Set-Content -Path $envPath -Encoding UTF8

Write-Host "Claude Desktop config updated: $ConfigPath"
Write-Host "Local env written: $envPath"
Write-Host "Restart Claude Desktop completely, then use MCP server: $Name"
